### PR TITLE
Task-49414 : [User management ]- Advanced filter doesn't work correctly after migration from 6.1.5 to 6.2.0 and 6.3.x

### PR DESCRIPTION
**Pull request by rdenarie**
ISSUES : users who haven't been connected after migration are displayed on the list of not connected.
Fix : This fix is an upgrade plugin that  will use the value lastLoginTime of each user and updated the profile , so i added i new module with the name data-upgrade-users

### CODE REVIEW

**Review by hbenali — COMMENTED** [review]
Would it needed to have this upgrade plugin for the `6.2.x`? I saw this task was created for a customer who does not use `6.2.x`. Having this upgrade for the (potential) latest maintenance version would be not needed. Thanks. cc @bourasom @halaya

**Comment by rdenarie** [comment]
@hbenali I asked on the task on tribe. I wait for the answer

**Comment by rdenarie** [comment]
I just received the answser. The initial customer which make the report is on CI/CD, but some other customer still on 6.2.4 make the same report.
So the backport is needed

**Comment by hbenali** [comment]
A decision was made to do not to backport this. This upgrade plugin has to be available for the PLF 6.3.x

**Pull request closed without merging**
